spring.application.name=bakend
spring.datasource.url=jdbc:postgresql://localhost:5432/documenti
spring.datasource.username=documenti
spring.datasource.password=documenti123
spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=update
